---
- hosts: localhost
  connection: local

  tasks:
    - set_fact:
        k8s_namespace: video-downloader-front-end
        hostname: video.home.ruchij.com
        aws_ssm_k8s_config: /infrastructure/prod/k8s/config

    - name: Deploy to production
      import_tasks: tasks/k8s-deploy.yml

    - name: Create GitHub release
      import_tasks: tasks/github-release.yml